# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: cimg/go:1.19

    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: (cd v2 && go test -v ./... -coverprofile=coverage.txt -covermode=count )
      - run:
          name: "Codecov upload"
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: "Install tools"
          command: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2
      - run:
          name: "Lint"
          command: (cd v2 && golangci-lint run)

